"""empty message

Revision ID: 16f11c2a0ffd
Revises: 266bb988377c
Create Date: 2015-04-07 16:48:40.411074

"""

# revision identifiers, used by Alembic.
revision = '16f11c2a0ffd'
down_revision = '266bb988377c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
