"""empty message

Revision ID: 1d9fc2ad5d76
Revises: 57b30fdeb2ab
Create Date: 2015-04-07 19:49:40.032853

"""

# revision identifiers, used by Alembic.
revision = '1d9fc2ad5d76'
down_revision = '57b30fdeb2ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.Column('source_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_user', sa.Integer(), nullable=True),
    sa.Column('end_user', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('posts')
    ### end Alembic commands ###
