"""empty message

Revision ID: 22000627f07a
Revises: 4fe34588268f
Create Date: 2015-04-07 14:07:39.298073

"""

# revision identifiers, used by Alembic.
revision = '22000627f07a'
down_revision = '4fe34588268f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
