"""empty message

Revision ID: 266bb988377c
Revises: 35cdcebf503b
Create Date: 2015-04-07 16:24:37.873822

"""

# revision identifiers, used by Alembic.
revision = '266bb988377c'
down_revision = '35cdcebf503b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
