"""empty message

Revision ID: 35cdcebf503b
Revises: 35f4c413bc9c
Create Date: 2015-04-07 16:23:37.048055

"""

# revision identifiers, used by Alembic.
revision = '35cdcebf503b'
down_revision = '35f4c413bc9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_user', sa.String(length=64), nullable=True),
    sa.Column('end_user', sa.String(length=64), nullable=True),
    sa.Column('end_user_id', sa.String(length=300), nullable=True),
    sa.Column('end_user_pic_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_friends')
    ### end Alembic commands ###
