"""empty message

Revision ID: 35f4c413bc9c
Revises: 22000627f07a
Create Date: 2015-04-07 14:15:21.143766

"""

# revision identifiers, used by Alembic.
revision = '35f4c413bc9c'
down_revision = '22000627f07a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__preferences')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__preferences',
    sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('preferences', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('last_accessed', mysql.DATETIME(), nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
