"""empty message

Revision ID: 3d541489e5c2
Revises: 543895dd2068
Create Date: 2015-04-07 23:43:34.841893

"""

# revision identifiers, used by Alembic.
revision = '3d541489e5c2'
down_revision = '543895dd2068'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
