"""empty message

Revision ID: 523f2dc78609
Revises: 3d541489e5c2
Create Date: 2015-04-08 00:12:08.195966

"""

# revision identifiers, used by Alembic.
revision = '523f2dc78609'
down_revision = '3d541489e5c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    ### end Alembic commands ###
