"""empty message

Revision ID: 543895dd2068
Revises: e931f02f5f6
Create Date: 2015-04-07 23:43:14.611108

"""

# revision identifiers, used by Alembic.
revision = '543895dd2068'
down_revision = 'e931f02f5f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_user_id', sa.Integer(), nullable=True),
    sa.Column('end_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_friends')
    ### end Alembic commands ###
