"""empty message

Revision ID: 57b30fdeb2ab
Revises: 16f11c2a0ffd
Create Date: 2015-04-07 19:48:37.544887

"""

# revision identifiers, used by Alembic.
revision = '57b30fdeb2ab'
down_revision = '16f11c2a0ffd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
