"""empty message

Revision ID: 58b8586635de
Revises: 523f2dc78609
Create Date: 2015-04-08 00:12:16.011906

"""

# revision identifiers, used by Alembic.
revision = '58b8586635de'
down_revision = '523f2dc78609'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
