"""empty message

Revision ID: e931f02f5f6
Revises: 1d9fc2ad5d76
Create Date: 2015-04-07 19:50:03.081830

"""

# revision identifiers, used by Alembic.
revision = 'e931f02f5f6'
down_revision = '1d9fc2ad5d76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
