"""empty message

Revision ID: f6fe3a23d03
Revises: 3c3547095a18
Create Date: 2015-04-08 03:00:09.714930

"""

# revision identifiers, used by Alembic.
revision = 'f6fe3a23d03'
down_revision = '3c3547095a18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
